// Mocks generated by Mockito 5.3.1 from annotations
// in attendance_app/test/app/user_attendance/provider/user_attendance_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:attendance_app/app/user_attendance/data/attendance_source_local.dart'
    as _i3;
import 'package:attendance_app/app/user_attendance/models/attendance_model.dart'
    as _i4;
import 'package:isar/isar.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIsar_0 extends _i1.SmartFake implements _i2.Isar {
  _FakeIsar_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AttendanceSourceLocal].
///
/// See the documentation for Mockito's code generation for more information.
class MockAttendanceSourceLocal extends _i1.Mock
    implements _i3.AttendanceSourceLocal {
  @override
  _i2.Isar get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeIsar_0(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeIsar_0(
          this,
          Invocation.getter(#db),
        ),
      ) as _i2.Isar);
  @override
  set db(_i2.Isar? _db) => super.noSuchMethod(
        Invocation.setter(
          #db,
          _db,
        ),
        returnValueForMissingStub: null,
      );
  @override
  dynamic whereDate(DateTime? value) => super.noSuchMethod(
        Invocation.method(
          #whereDate,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  dynamic create(_i4.AttendanceModel? model) => super.noSuchMethod(
        Invocation.method(
          #create,
          [model],
        ),
        returnValueForMissingStub: null,
      );
  @override
  dynamic update(_i4.AttendanceModel? model) => super.noSuchMethod(
        Invocation.method(
          #update,
          [model],
        ),
        returnValueForMissingStub: null,
      );
}
